# Generated by Django 5.2.12 on 2026-03-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_at'],
            },
        ),
    ]
